/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3D/can_original.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three';

export function Model({ texture, ...props }) {
  const { nodes, materials } = useGLTF('/3D/can_original.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        scale={10}
        geometry={nodes.can_original.geometry}
        // material={materials.Pepsi_can}
        position={[0.11, 0.123, 0]}
        rotation={[-Math.PI / 2, 0, 9.1]}
      >
        {/* <meshStandardMaterial
          color={color}
          metalness={0.7} // Gives it a metallic look
          roughness={0.2} // Makes it shiny
        /> */}
        <meshStandardMaterial
          // The `map` property is where you apply the main color texture.
          // This replaces the `color` property.
          map={texture} 
          metalness={0.5}
          roughness={0.2}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/can_original.glb')
