/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3D/vinrsr_logo_3d.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3D/vinrsr_logo_3d.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_logo.geometry} material={nodes.mesh_logo.material} rotation={[Math.PI / 2, 0, 0]} scale={[5, 1, 5]} />
    </group>
  )
}

useGLTF.preload('/vinrsr_logo_3d.glb')
